CREATE Table users_full_details (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    profile_img VARCHAR(200),
    DOB DATE NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    address_line1 VARCHAR(200) not NULL,
    address_line2 VARCHAR(200),
    city VARCHAR(100) not NULL,
    state VARCHAR(100) not NULL,
    pin_code VARCHAR(20) not NULL,
    country VARCHAR(100) not NULL,
    nationality VARCHAR(100) not NULL,
    passport_number VARCHAR(50) not NULL,
    preferred_airport VARCHAR(100),
    preferred_seat VARCHAR(100),
    dietary_preferences VARCHAR(200),
    medical_notes VARCHAR(500),
    Emergency_contact_name VARCHAR(100),
    Emergency_contact_number VARCHAR(20),
    Emergency_contact_relationship VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) on DELETE CASCADE,
    index idx_user_id (user_id)
)